Repository hhu-propra2/abschlussprojekt-die-senioren, pull requests merged in 2020-03, with the labels that each got.

#50 Feature/41 controller and front end
  build.gradle
  src/main/java/mops/gruppen1/Controller/GroupController.java
  src/main/resources/templates/index.html
  src/test/java/mops/gruppen1/Controller/GroupControllerTest.java
Labels: enhancement

#61 Modify method signature in Event class of execute function
  src/main/java/mops/gruppen1/applicationService/GroupService.java
  src/main/java/mops/gruppen1/domain/events/AppointmentCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/AppointmentDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/AssignmentCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/Event.java
  src/main/java/mops/gruppen1/domain/events/ForumCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupPropertyUpdateEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberResignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAcceptanceEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAssignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRejectionEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRequestEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipUpdateEvent.java
  src/main/java/mops/gruppen1/domain/events/UserCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/UserDeactivationEvent.java
  src/main/java/mops/gruppen1/domain/events/UserUpdateEvent.java
Labels: enhancement

#93 Feature/84 create event dto
  src/main/java/mops/gruppen1/applicationService/EventService.java
  src/main/java/mops/gruppen1/applicationService/GroupService.java
  src/main/java/mops/gruppen1/domain/Group.java
  src/main/java/mops/gruppen1/domain/events/GroupCreationEvent.java
  src/test/java/mops/gruppen1/applicationService/GroupServiceTest.java
Labels: branch

#101 Feature/89 add javadoc for event classes
  src/main/java/mops/gruppen1/domain/Group.java
  src/main/java/mops/gruppen1/domain/GroupStatus.java
  src/main/java/mops/gruppen1/domain/Status.java
  src/main/java/mops/gruppen1/domain/User.java
  src/main/java/mops/gruppen1/domain/Username.java
  src/main/java/mops/gruppen1/domain/events/AppointmentCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/AppointmentDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/Event.java
  src/main/java/mops/gruppen1/domain/events/ForumCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupPropertyUpdateEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberResignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAcceptanceEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAssignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRejectionEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRequestEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipUpdateEvent.java
  src/main/java/mops/gruppen1/domain/events/UserCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/UserDeactivationEvent.java
  src/main/java/mops/gruppen1/domain/events/UserUpdateEvent.java
Labels: Event

#110 Feature/74 group deletion event
  src/main/java/mops/gruppen1/applicationService/GroupService.java
  src/main/java/mops/gruppen1/domain/Group.java
  src/main/java/mops/gruppen1/domain/Membership.java
  src/main/java/mops/gruppen1/domain/events/AppointmentCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/AppointmentDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/AssignmentCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/Event.java
  src/main/java/mops/gruppen1/domain/events/ForumCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupPropertyUpdateEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberResignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAcceptanceEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAssignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRejectionEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRequestEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipUpdateEvent.java
  src/main/java/mops/gruppen1/domain/events/TestEvent.java
  src/main/java/mops/gruppen1/domain/events/UserCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/UserDeactivationEvent.java
  src/main/java/mops/gruppen1/domain/events/UserUpdateEvent.java
Labels: branch

#124 Feature/112 test set up
  src/test/java/mops/gruppen1/domain/events/GroupCreationEventTest.java
  src/test/java/mops/gruppen1/domain/events/TestSetup.java
Labels: branch

#173 Feature/96 group service
  src/main/java/mops/gruppen1/applicationService/GroupService.java
  src/main/java/mops/gruppen1/applicationService/ValidationResult.java
  src/main/java/mops/gruppen1/data/EventRepo.java
  src/main/java/mops/gruppen1/domain/Group.java
  src/main/java/mops/gruppen1/domain/Membership.java
  src/main/java/mops/gruppen1/domain/MembershipStatus.java
  src/main/java/mops/gruppen1/domain/MembershipType.java
  src/main/java/mops/gruppen1/domain/events/AppointmentCreationEvent.java
  src/main/java/mops/gruppen1/domain/events/AppointmentDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/GroupDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MaterialDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberResignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAcceptanceEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAssignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRejectionEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRequestEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipUpdateEvent.java
  src/test/java/mops/gruppen1/domain/events/MemberDeletionEventTest.java
  src/test/java/mops/gruppen1/domain/events/MemberResignmentEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipAcceptanceEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipAssignmentEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipRejectionEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipUpdateEventTest.java
  src/test/java/mops/gruppen1/domain/events/TestSetup.java
Labels: branch

#162 Rename Type to MembershipType in all files
  src/main/java/mops/gruppen1/domain/Group.java
  src/main/java/mops/gruppen1/domain/Membership.java
  src/main/java/mops/gruppen1/domain/MembershipStatus.java
  src/main/java/mops/gruppen1/domain/MembershipType.java
  src/main/java/mops/gruppen1/domain/events/MemberDeletionEvent.java
  src/main/java/mops/gruppen1/domain/events/MemberResignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAcceptanceEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipAssignmentEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRejectionEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipRequestEvent.java
  src/main/java/mops/gruppen1/domain/events/MembershipUpdateEvent.java
  src/test/java/mops/gruppen1/domain/events/MemberDeletionEventTest.java
  src/test/java/mops/gruppen1/domain/events/MemberResignmentEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipAcceptanceEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipAssignmentEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipRejectionEventTest.java
  src/test/java/mops/gruppen1/domain/events/MembershipUpdateEventTest.java
  src/test/java/mops/gruppen1/domain/events/TestSetup.java
Labels: enhancement

#174 Feature/165 membership request event test
  src/main/java/mops/gruppen1/domain/events/MembershipRequestEvent.java
  src/test/java/mops/gruppen1/domain/events/MembershipRequestEventTest.java
Labels: branch, bug

#184 Feature/172 test data
  src/main/java/mops/gruppen1/data/EventDTO.java
  src/main/resources/data.sql
  src/test/resources/application.properties
Labels: enhancement
